controller_list:
  - name: ""
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints:
      - ovis_joint_1
      - ovis_joint_2
      - ovis_joint_3
      - ovis_joint_4
      - ovis_joint_5
      - ovis_joint_6
  # - name: /ovis/gripper_controller
  #   action_ns: gripper_cmd
  #   type: GripperCommand
  #   default: true
  #   joints:
  #     - finger_joint