controller_list:
  - name: fake_manipulator_controller
    joints:
      - ovis_joint_1
      - ovis_joint_2
      - ovis_joint_3
      - ovis_joint_4
      - ovis_joint_5
      - ovis_joint_6
  # - name: fake_gripper_controller
  #   joints:
  #     - finger_joint